# 3️⃣ Create minimal dummy kernel folder & main.c
      - name: Create dummy kernel
        run: |
          mkdir -p kernel/arch/arm64/configs
          mkdir -p out
          echo 'CONFIG_ARM64=y' > kernel/arch/arm64/configs/dummy_defconfig
          echo 'obj-y := main.o' > kernel/Makefile
          cat << 'EOF' > kernel/main.c
          #include <stdio.h>

          int main() {
              printf("Dummy Kernel Build Test\n");
              return 0;
          }
          EOF
